apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-gitops-cloud-deploy
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-gitops-cloud-deploy
                port: 
                  number: 80