apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: go-app-green
images:
- name: hello-gitops-cloud-deploy
  newName: vverbytskyi/hello-gitops-cloud-deploy
  newTag: 7344390200b97703c42c1978fef34f842a96fff7
