apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: go-app-blue
images:
- name: hello-gitops-cloud-deploy
  newName: vverbytskyi/hello-gitops-cloud-deploy
  newTag: f91826b1f991d742fd1da06a4a87d87cef881c2d
